//
// Created by matt on 03.05.17.
//

#ifndef OPENGL_CPP_BACKBONE2_DIRECTIONS_H
#define OPENGL_CPP_BACKBONE2_DIRECTIONS_H


enum Direction {LEFT,RIGHT,FORWARD,BACKWARD,UP,DOWN};

#endif //OPENGL_CPP_BACKBONE2_DIRECTIONS_H
